food_info_facts = {
        'apple_pie': 'Apple pie is a classic American dessert made from sliced apples and pastry crust.',
        'baby_back_ribs': 'Baby back ribs are a popular barbecue dish, known for their tender and flavorful meat.',
        'baklava': 'Baklava is a sweet pastry dessert made of layers of filo dough, filled with nuts and honey.',
        'beef_carpaccio': 'Beef carpaccio is an Italian dish consisting of thinly sliced raw beef, often served as an appetizer.',
        'beef_tartare': 'Beef tartare is a French dish made from finely chopped or minced raw beef, typically seasoned with herbs and spices.',
        'beet_salad': 'Beet salad is a healthy and colorful dish made from roasted or boiled beets, often served with goat cheese and greens.',
        'beignets': 'Beignets are a popular French pastry, similar to doughnuts, and are often served with powdered sugar on top.',
        'bibimbap': 'Bibimbap is a Korean dish that features rice, mixed vegetables, and meat, usually topped with a spicy sauce.',
        'bread_pudding': 'Bread pudding is a comforting dessert made from stale bread soaked in a mixture of milk, eggs, and sugar.',
        'breakfast_burrito': 'A breakfast burrito is a hearty morning meal wrapped in a tortilla and filled with ingredients like eggs, bacon, and cheese.',
        'bruschetta': 'Bruschetta is an Italian appetizer consisting of grilled bread rubbed with garlic and topped with diced tomatoes, basil, and olive oil.',
        'caesar_salad': 'Caesar salad is a popular salad made with romaine lettuce, croutons, Parmesan cheese, and Caesar dressing.',
        'cannoli': 'Cannoli are Italian pastries filled with sweet ricotta cheese and often decorated with chocolate chips or pistachios.',
        'caprese_salad': 'Caprese salad is a simple Italian dish made with fresh mozzarella cheese, tomatoes, basil, olive oil, and balsamic vinegar.',
        'carrot_cake': 'Carrot cake is a moist and flavorful dessert made with grated carrots and usually topped with cream cheese frosting.',
        'ceviche': 'Ceviche is a Latin American dish made from fresh seafood or fish marinated in citrus juices, often served with onions, cilantro, and peppers.',
        'cheesecake': 'Cheesecake is a rich and creamy dessert made with cream cheese, sugar, and a graham cracker crust.',
        'cheese_plate': 'A cheese plate is a delightful assortment of cheeses, often accompanied by crackers, fruits, and nuts.',
        'chicken_curry': 'Did you know that chicken curry is a staple in many Asian cuisines?',
        'chicken_quesadilla': 'Chicken quesadilla is a Mexican dish made by folding a tortilla filled with chicken and cheese.',
        'chicken_wings': 'Chicken wings are believed to have originated in Buffalo, New York, in the 1960s.',
        'chocolate_cake': 'Chocolate cake is a beloved dessert made with chocolate-flavored batter and often covered in chocolate frosting or ganache.',
        'chocolate_mousse': 'Chocolate mousse is a decadent dessert made with whipped chocolate and cream, creating a light and airy texture.',
        'churros': 'Churros are a popular Spanish snack made from fried dough, often coated in sugar and cinnamon.',
        'clam_chowder': 'Clam chowder is a creamy soup made with clams, potatoes, onions, and sometimes bacon.',
        'club_sandwich': 'A club sandwich is a stacked sandwich made with layers of turkey or chicken, bacon, lettuce, and tomato.',
        'crab_cakes': 'Crab cakes are delicious patties made from crab meat, breadcrumbs, and various seasonings.',
        'creme_brulee': 'Creme brulee is a French dessert consisting of a creamy custard base topped with a layer of caramelized sugar.',
        'croque_madame': 'Croque madame is a French sandwich made with ham and cheese, topped with a fried or poached egg.',
        'cup_cakes': 'Cupcakes are small, individual-sized cakes often decorated with colorful frosting and sprinkles.',
        'deviled_eggs': 'Deviled eggs are hard-boiled eggs that have been cut in half and filled with a seasoned yolk mixture.',
        'donuts': 'Donuts, also spelled doughnuts, are sweet fried pastries that come in various flavors and toppings.',
        'dumplings': 'Dumplings are a versatile dish found in many cuisines, consisting of dough filled with meat, vegetables, or other ingredients.',
        'edamame': 'Edamame are young soybean pods that are often boiled or steamed and served as a healthy snack.',
        'eggs_benedict': 'Eggs Benedict is a classic brunch dish made with poached eggs, Canadian bacon, and hollandaise sauce on an English muffin.',
        'escargots': 'Escargots are a French delicacy of cooked snails, often served with garlic butter and parsley.',
        'falafel': 'Falafel is a popular Middle Eastern dish made from deep-fried ground chickpeas or fava beans, typically served in pita bread with tahini sauce.',
        'filet_mignon': 'Filet mignon is a tender and premium cut of beef, known for its melt-in-your-mouth texture.',
        'fish_and_chips': 'Fish and chips is a classic British dish consisting of deep-fried fish and thick-cut potato fries, often served with vinegar or tartar sauce.',
        'foie_gras': 'Foie gras is a luxury food product made from the liver of a duck or goose that has been specially fattened.',
        'french_fries': 'French fries are a beloved side dish made from deep-fried potato sticks, often served with ketchup or other condiments.',
        'french_onion_soup': 'French onion soup is a savory soup made with caramelized onions, beef broth, and melted cheese on top.',
        'french_toast': 'French toast is a breakfast dish made by dipping slices of bread in a mixture of eggs, milk, and spices, then frying until golden brown.',
        'fried_calamari': 'Fried calamari is a popular appetizer made from deep-fried squid rings, often served with marinara sauce or aioli.',
        'fried_rice': 'Fried rice is a popular dish in Chinese cuisine and can be traced back to the Sui Dynasty.',
        'frozen_yogurt': 'Frozen yogurt is a frozen dessert similar to ice cream but made with yogurt instead of cream.',
        'garlic_bread': 'Garlic bread is a simple and flavorful side dish made with sliced bread, butter, and garlic, often toasted until crispy.',
        'gnocchi': 'Gnocchi are Italian potato dumplings, often served with various sauces such as pesto or marinara.',
        'greek_salad': 'Greek salad is a refreshing dish made with tomatoes, cucumbers, olives, feta cheese, and a lemon-oregano dressing.',
        'grilled_cheese_sandwich': 'A grilled cheese sandwich is a classic comfort food made by grilling bread with cheese in the middle until crispy and melted.',
        'grilled_salmon': 'Salmon is rich in omega-3 fatty acids, which are good for heart health.',
        'guacamole': 'Guacamole is a Mexican dip made from mashed avocados, onions, tomatoes, and various seasonings.',
        'gyoza': 'Gyoza are Japanese dumplings filled with ground meat and vegetables, often pan-fried and served with dipping sauce.',
        'hamburger': 'The hamburger is a classic American dish and has a disputed origin between various U.S. cities.',
        'hot_and_sour_soup': 'Hot and sour soup is a popular Chinese soup known for its spicy and tangy flavor, often made with tofu and vegetables.',
        'hot_dog': 'A hot dog is a cooked sausage served in a sliced bun, typically garnished with mustard, ketchup, onions, and other toppings.',
        'huevos_rancheros': 'Huevos rancheros is a Mexican breakfast dish made with fried eggs served on corn tortillas and topped with tomato-chili sauce.',
        'hummus': 'Hummus is a Middle Eastern dip made from mashed chickpeas, tahini, lemon juice, and garlic, often served with pita bread.',
        'ice_cream': 'The world\'s largest ice cream cone, made in Norway, measured over 3 meters tall!',
        'lasagna': 'Lasagna is a classic Italian pasta dish made with layers of pasta, ricotta cheese, mozzarella, and tomato sauce.',
        'lobster_bisque': 'Lobster bisque is a creamy and flavorful soup made from lobster meat and shellfish stock.',
        'lobster_roll_sandwich': 'A lobster roll sandwich is a New England specialty made with lobster meat tossed in mayonnaise and served in a toasted roll.',
        'macaroni_and_cheese': 'Macaroni and cheese is a comfort food dish made with cooked pasta and a creamy cheese sauce.',
        'macarons': 'Macarons are delicate French pastries made from almond meringue cookies filled with ganache, buttercream, or jam.',
        'miso_soup': 'Miso soup is a traditional Japanese soup made with fermented soybean paste and often includes tofu, seaweed, and green onions.',
        'mussels': 'Mussels are shellfish that are commonly steamed in a broth made with white wine, garlic, and herbs.',
        'nachos': 'Nachos are a popular snack or appetizer made with tortilla chips topped with melted cheese and various toppings like jalapeños and sour cream.',
        'omelette': 'An omelette is a savory dish made from beaten eggs cooked with fillings like cheese, vegetables, and meats.',
        'onion_rings': 'Onion rings are a crispy and flavorful snack made by dipping onion slices in batter and deep-frying them.',
        'oysters': 'Oysters are a type of shellfish that are often served raw on the half shell or cooked in various dishes.',
        'pad_thai': 'Pad Thai is a popular Thai stir-fried noodle dish made with rice noodles, tofu, shrimp, or chicken, and a tangy sauce.',
        'paella': 'Paella is a Spanish rice dish cooked with saffron, vegetables, and a variety of proteins, such as chicken, seafood, or rabbit.',
        'pancakes': 'Pancakes are a breakfast favorite made from a batter of flour, eggs, milk, and baking powder, often served with syrup or toppings.',
        'panna_cotta': 'Panna cotta is an Italian dessert made with sweetened cream, gelatin, and vanilla, often topped with fruit or caramel sauce.',
        'peking_duck': 'Peking duck is a famous Chinese dish known for its crispy skin and tender meat, often served with hoisin sauce and thin pancakes.',
        'pho': 'Pho is a Vietnamese noodle soup made with beef or chicken, rice noodles, and a flavorful broth.',
        'pizza': 'Pizza has its roots in Italy and has become a global favorite with countless variations.',
        'pork_chop': 'A pork chop is a cut of pork often grilled, fried, or roasted, and can be served with various sauces and seasonings.',
        'poutine': 'Poutine is a Canadian dish made with french fries topped with cheese curds and smothered in gravy.',
        'prime_rib': 'Prime rib is a tender and flavorful cut of beef often roasted to perfection and served with au jus.',
        'pulled_pork_sandwich': 'A pulled pork sandwich is made from slow-cooked, shredded pork shoulder, often served with barbecue sauce and coleslaw.',
        'ramen': 'Ramen is a Japanese dish that consists of Chinese-style wheat noodles served in a meat or fish-based broth.',
        'ravioli': 'Ravioli are Italian dumplings filled with various ingredients like cheese, meat, or vegetables, often served with pasta sauce.',
        'red_velvet_cake': 'Red velvet cake is a moist and velvety dessert known for its distinctive red color and cream cheese frosting.',
        'risotto': 'Risotto is an Italian rice dish cooked with broth until creamy and often flavored with ingredients like mushrooms, seafood, or saffron.',
        'samosa': 'Samosa is a popular Indian snack made from pastry filled with spiced potatoes, peas, and sometimes meat.',
        'sashimi': 'Sashimi is a Japanese dish consisting of thinly sliced raw fish or seafood, often served with soy sauce and wasabi.',
        'scallops': 'Scallops are seafood delicacies known for their sweet and tender flesh, often pan-seared or grilled.',
        'seaweed_salad': 'Seaweed salad is a refreshing Japanese dish made from various types of seaweed, often dressed with sesame oil and vinegar.',
        'shrimp_and_grits': 'Shrimp and grits is a classic Southern dish made with creamy grits and sautéed shrimp, often flavored with bacon and spices.',
        'spaghetti_bolognese': 'Spaghetti Bolognese is an Italian pasta dish with a meaty tomato sauce, often served with grated Parmesan cheese.',
        'spaghetti_carbonara': 'Spaghetti Carbonara is an Italian pasta dish made with eggs, cheese, pancetta, and black pepper, creating a creamy sauce.',
        'spring_rolls': 'Spring rolls are a popular Asian appetizer made with thin rice paper wrappers filled with vegetables, shrimp, or other ingredients.',
        'steak': 'A perfectly cooked steak is a culinary delight, with preferences ranging from rare to well-done.',
        'strawberry_shortcake': 'Strawberry shortcake is a classic dessert made with layers of sponge cake, fresh strawberries, and whipped cream.',
        'sushi': 'Sushi is a traditional Japanese dish that typically consists of vinegared rice and various ingredients like seafood and vegetables.',
        'tacos': 'Tacos are a Mexican street food favorite made with tortillas filled with a variety of ingredients like meat, beans, and salsa.',
        'takoyaki': 'Takoyaki are Japanese octopus balls, typically filled with diced octopus and topped with savory sauces and bonito flakes.',
        'tiramisu': 'Tiramisu is an Italian dessert made with layers of coffee-soaked ladyfingers and mascarpone cheese, often dusted with cocoa powder.',
        'tuna_tartare': 'Tuna tartare is a dish made from finely chopped raw tuna, often mixed with seasonings like soy sauce, sesame oil, and avocado.',
        'waffles': 'Waffles are a breakfast favorite made from a batter poured into a waffle iron, resulting in crispy and fluffy waffles, often served with syrup and toppings.'
    }